SELECT MARCA,
EXTRACT(YEAR FROM DATA_VENDA) AS ANO,
EXTRACT(MONTH FROM DATA_VENDA) AS MES,
SUM(QTD_VENDA) AS QTD_VENDA
FROM `alert-streamer-286501.REF_VENDA_BOTICARIO.TB_VENDAS`
GROUP BY MARCA, ANO, MES